package com.example.packing_iso_service.util;

import java.util.Map;

public class ISOFieldNames {

    public static final Map<Integer, String> FIELD_NAMES = Map.ofEntries(
            Map.entry(1, "Bitmap Secondary"),
            Map.entry(2, "Primary Account Number"),
            Map.entry(3, "Processing Code"),
            Map.entry(4, "Transaction Amount"),
            Map.entry(5, "Settlement Amount"),
            Map.entry(6, "Cardholder Billing Amount"),
            Map.entry(7, "Transmission Date & Time"),
            Map.entry(8, "Cardholder Billing Fee"),
            Map.entry(9, "Conversion Rate, Settlement"),
            Map.entry(10, "Conversion Rate, Cardholder Billing"),
            Map.entry(11, "STAN"),
            Map.entry(12, "Local Time"),
            Map.entry(13, "Local Date"),
            Map.entry(14, "Expiration Date"),
            Map.entry(15, "Settlement Date"),
            Map.entry(16, "Currency Conversion Date"),
            Map.entry(17, "Capture Date"),
            Map.entry(18, "Merchant Type"),
            Map.entry(19, "Acquiring Institution Country Code"),
            Map.entry(20, "PAN Extended Country Code"),
            Map.entry(21, "Forwarding Institution Country Code"),
            Map.entry(22, "POS Entry Mode"),
            Map.entry(23, "Card Sequence Number"),
            Map.entry(24, "Network International Identifier"),
            Map.entry(25, "POS Condition Code"),
            Map.entry(26, "POS PIN Capture Code"),
            Map.entry(27, "Authorizing Identification Response Length"),
            Map.entry(28, "Transaction Fee"),
            Map.entry(29, "Settlement Fee"),
            Map.entry(30, "Transaction Processing Fee"),
            Map.entry(31, "Settlement Processing Fee"),
            Map.entry(32, "Acquiring Institution ID Code"),
            Map.entry(33, "Forwarding Institution ID Code"),
            Map.entry(34, "PAN Extended"),
            Map.entry(35, "Track 2 Data"),
            Map.entry(36, "Track 3 Data"),
            Map.entry(37, "RRN"),
            Map.entry(38, "Authorization ID Response"),
            Map.entry(39, "Response Code"),
            Map.entry(40, "Service Restriction Code"),
            Map.entry(41, "Terminal ID"),
            Map.entry(42, "Card Acceptor ID Code"),
            Map.entry(43, "Card Acceptor Name/Location"),
            Map.entry(44, "Additional Response Data"),
            Map.entry(45, "Track 1 Data"),
            Map.entry(46, "Additional Data - ISO"),
            Map.entry(47, "Additional Data - National"),
            Map.entry(48, "Additional Data - Private"),
            Map.entry(49, "Currency Code"),
            Map.entry(50, "Settlement Currency Code"),
            Map.entry(51, "Cardholder Billing Currency Code"),
            Map.entry(52, "PIN Data"),
            Map.entry(53, "Security Related Control Info"),
            Map.entry(54, "Additional Amounts"),
            Map.entry(55, "IC Card System Data"),
            Map.entry(56, "Reserved ISO"),
            Map.entry(57, "Reserved National"),
            Map.entry(58, "Reserved National"),
            Map.entry(59, "Reserved National"),
            Map.entry(60, "Reserved Private"),
            Map.entry(61, "Reserved Private"),
            Map.entry(62, "Reserved Private"),
            Map.entry(63, "Reserved Private"),
            Map.entry(64, "MAC"),
            Map.entry(65, "Bitmap Extended"),
            Map.entry(66, "Settlement Code"),
            Map.entry(67, "Extended Payment Code"),
            Map.entry(68, "Receiving Institution Country Code"),
            Map.entry(69, "Settlement Institution Country Code"),
            Map.entry(70, "Network Management Information Code"),
            Map.entry(71, "Message Number"),
            Map.entry(72, "Message Number Last"),
            Map.entry(73, "Date Action"),
            Map.entry(74, "Credits Number"),
            Map.entry(75, "Credits Reversal Number"),
            Map.entry(76, "Debits Number"),
            Map.entry(77, "Debits Reversal Number"),
            Map.entry(78, "Transfer Number"),
            Map.entry(79, "Transfer Reversal Number"),
            Map.entry(80, "Inquiries Number"),
            Map.entry(81, "Authorizations Number"),
            Map.entry(82, "Credits Processing Fee Amount"),
            Map.entry(83, "Credits Transaction Fee Amount"),
            Map.entry(84, "Debits Processing Fee Amount"),
            Map.entry(85, "Debits Transaction Fee Amount"),
            Map.entry(86, "Credits Amount"),
            Map.entry(87, "Debits Amount"),
            Map.entry(88, "Credits Reversal Amount"),
            Map.entry(89, "Debits Reversal Amount"),
            Map.entry(90, "Original Data Elements"),
            Map.entry(91, "File Update Code"),
            Map.entry(92, "File Security Code"),
            Map.entry(93, "Response Indicator"),
            Map.entry(94, "Service Indicator"),
            Map.entry(95, "Replacement Amounts"),
            Map.entry(96, "Message Security Code"),
            Map.entry(97, "Net Settlement Amount"),
            Map.entry(98, "Payee"),
            Map.entry(99, "Settlement Institution ID Code"),
            Map.entry(100, "Receiving Institution ID Code"),
            Map.entry(101, "File Name"),
            Map.entry(102, "Account Identification 1"),
            Map.entry(103, "Account Identification 2"),
            Map.entry(104, "Transaction Description"),
            Map.entry(105, "Reserved ISO"),
            Map.entry(106, "Reserved ISO"),
            Map.entry(107, "Reserved ISO"),
            Map.entry(108, "Reserved ISO"),
            Map.entry(109, "Reserved ISO"),
            Map.entry(110, "Reserved ISO"),
            Map.entry(111, "Reserved ISO"),
            Map.entry(112, "Reserved National"),
            Map.entry(113, "Reserved National"),
            Map.entry(114, "Reserved National"),
            Map.entry(115, "Reserved National"),
            Map.entry(116, "Reserved National"),
            Map.entry(117, "Reserved National"),
            Map.entry(118, "Reserved National"),
            Map.entry(119, "Reserved National"),
            Map.entry(120, "Reserved Private"),
            Map.entry(121, "Reserved Private"),
            Map.entry(122, "Reserved Private"),
            Map.entry(123, "Reserved Private"),
            Map.entry(124, "Reserved Private"),
            Map.entry(125, "Reserved Private"),
            Map.entry(126, "Reserved Private"),
            Map.entry(127, "Reserved Private"),
            Map.entry(128, "MAC Extended")
    );
}
